#!/usr/bin/env bash

# Initialize a counter
counter=0

# Define the maximum number of iterations
max_iterations=10

# Use a while loop to display "Best School" 10 times
while [ $counter -lt $max_iterations ]; do
    echo "Best School"
    
    # Increment the counter
    ((counter++))
done
